title: Gobi Tutoring Services
email: gobi.tutoring.services@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Ontario Curriculum-Aligned STEM Tutoring for Grades 6–12 | 
  Math, Science, Technology & Engineering | 
  Online & In-Person Sessions
baseurl: "" # the subpath of your site, e.g. /blog
show_downloads: true
google_analytics:
theme: jekyll-theme-architect
